[package]
name = "math_lang_parser"
version = "0.1.0"
authors = ["Edwin Baeza <baeza.edwin216@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2" 
